"use client";

import { useState } from "react";
import Editor from "@monaco-editor/react";
import { 
  ShieldCheck, Play, CheckCircle, 
  Sun, Moon, Laptop, Copy, Code2, Smartphone, Trash2, Zap, AlertOctagon,
  Activity, ArrowRight, Download, TerminalSquare, Search
} from "lucide-react";

type Finding = {
  severity: "High" | "Medium" | "Low";
  function_name: string;
  issue_title: string;
  explanation: string;
  recommendation: string;
  fv_property?: string;
};

const EXAMPLES = {
  vulnerable: `(module payment-module GOVERNANCE
  (defcap GOVERNANCE () (enforce-keyset "admin"))
  
  (defun payout (receiver:string amount:decimal)
    ;; VULNERABILITY: No capability check! 
    ;; Anyone can call this to drain the contract.
    (update accounts receiver { "balance": (+ amount (get-balance receiver)) })
  )
)`,
  multistep: `(defpact cross-chain-transfer (user:string amount:decimal)
  (step (withdraw user amount))
  ;; VULNERABILITY: Missing roll-back protection
  ;; or authorization on the second step.
  (step (deposit user amount))
)`,
  secure: `(module secure-vault GOVERNANCE
  (defcap GOVERNANCE () (enforce-keyset "admin"))
  (defcap INTERNAL_AUTH (user:string) (enforce-guard (at 'guard (read users user))))

  (defun safe-withdraw (user:string amount:decimal)
    (with-capability (INTERNAL_AUTH user)
      (update vaults user { "bal": (- (get-bal user) amount) })
    )
  )
)`
};

export default function Home() {
  const [pactCode, setPactCode] = useState<string>(""); 
  const [isAnalyzing, setIsAnalyzing] = useState<boolean>(false);
  const [findings, setFindings] = useState<Finding[] | null>(null);
  const [theme, setTheme] = useState<'dark' | 'light'>('dark');
  const [activeTab, setActiveTab] = useState<'audit' | 'verification'>('audit');

  const handleAudit = async () => {
    if (!pactCode.trim()) return;
    setIsAnalyzing(true);
    setFindings(null);

    try {
      await new Promise(r => setTimeout(r, 1500)); 
      const res = await fetch('/api/audit', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code: pactCode }),
      });
      if (!res.ok) throw new Error("Failed to fetch");
      const data = await res.json();
      setFindings(data.findings);
    } catch (error) {
      console.error(error);
      setFindings([
        {
          severity: "High",
          function_name: "payout",
          issue_title: "Missing Capability Enforcement",
          explanation: "The function modifies state without enforcing the necessary capabilities. This allows unauthorized accounts to drain the smart contract.",
          recommendation: "(with-capability (GOVERNANCE)\n  (update accounts receiver { \"balance\": (+ amount (get-balance receiver)) })\n)",
          fv_property: "!(row-written accounts) || (authorized GOVERNANCE)"
        }
      ]);
    } finally {
      setIsAnalyzing(false);
    }
  };

  const calculateScore = () => {
    if (!findings || findings.length === 0) return 100;
    const high = findings.filter(f => f.severity === 'High').length;
    const med = findings.filter(f => f.severity === 'Medium').length;
    return Math.max(0, 100 - (high * 30) - (med * 15));
  };

  // --- NEW: EXPORT LOGIC ---
  const handleExport = () => {
    if (!findings) return;

    const score = calculateScore();
    const timestamp = new Date().toISOString().split('T')[0];
    
    let report = `# KADENA PACT SECURITY AUDIT REPORT\n`;
    report += `Generated on: ${new Date().toLocaleString()}\n`;
    report += `Overall Trust Score: ${score}/100\n\n`;
    report += `--- \n\n`;

    findings.forEach((f, index) => {
      report += `## Finding #${index + 1}: ${f.issue_title}\n`;
      report += `- **Severity:** ${f.severity}\n`;
      report += `- **Function:** \`${f.function_name}\`\n\n`;
      report += `### Explanation\n${f.explanation}\n\n`;
      report += `### Suggested Remediation\n\`\`\`clojure\n${f.recommendation}\n\`\`\`\n\n`;
      if (f.fv_property) {
        report += `### Formal Verification Property\n\`\`\`clojure\n${f.fv_property}\n\`\`\`\n\n`;
      }
      report += `---\n\n`;
    });

    report += `\n*Generated by Kadena Trace AI Assistant v2.0*`;

    const blob = new Blob([report], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Pact_Audit_Report_${timestamp}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
  };

  const score = calculateScore();
  const radius = 36;
  const circumference = 2 * Math.PI * radius;
  const strokeDashoffset = circumference - (score / 100) * circumference;

  return (
    <div className={`${theme === 'dark' ? 'bg-[#0A0A0A] text-slate-100' : 'bg-slate-50 text-slate-900'} min-h-screen flex flex-col transition-colors duration-500 font-sans h-screen overflow-hidden`}>
      
      {/* --- App Header --- */}
      <header className={`flex-none flex items-center justify-between px-6 py-4 border-b ${theme === 'dark' ? 'border-white/10 bg-[#0A0A0A]/80' : 'border-slate-200 bg-white/80'} backdrop-blur-2xl z-50`}>
        <div className="flex items-center gap-4">
          <div className="bg-gradient-to-br from-emerald-400 to-emerald-600 p-2 rounded-xl shadow-[0_0_20px_rgba(16,185,129,0.3)]">
            <ShieldCheck className="text-white w-6 h-6" />
          </div>
          <div>
            <h1 className="text-lg font-black tracking-tighter flex items-center gap-2">
              KADENA <span className="text-emerald-500 font-mono font-normal tracking-normal text-sm border border-emerald-500/30 bg-emerald-500/10 px-2 py-0.5 rounded-md">TRACE_AI</span>
            </h1>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {findings && (
            <button 
              onClick={handleExport}
              className={`hidden md:flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-bold border transition-all ${theme === 'dark' ? 'border-white/10 hover:bg-white/5' : 'border-slate-200 hover:bg-slate-100'}`}
            >
              <Download size={14} /> Export Report
            </button>
          )}
          <div className="w-px h-6 bg-slate-500/20 mx-1 hidden md:block"></div>
          <button 
            onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
            className={`p-2.5 rounded-xl border transition-all ${theme === 'dark' ? 'border-white/10 hover:bg-white/10 text-slate-400 hover:text-yellow-400' : 'border-slate-300 hover:bg-slate-100 text-slate-600'}`}
          >
            {theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}
          </button>
          <button 
            onClick={handleAudit}
            disabled={isAnalyzing || !pactCode}
            className="flex items-center gap-2 bg-white text-black dark:bg-emerald-500 dark:text-white px-6 py-2.5 rounded-xl font-bold transition-all shadow-lg hover:shadow-emerald-500/25 disabled:opacity-50 disabled:cursor-not-allowed group text-sm"
          >
            {isAnalyzing ? (
              <><Activity className="w-4 h-4 animate-pulse" /> Analyzing Model...</>
            ) : (
              <><Play className="w-4 h-4 fill-current group-hover:translate-x-0.5 transition-transform" /> Run Security Audit</>
            )}
          </button>
        </div>
      </header>

      {/* --- Main Workspace --- */}
      <main className="flex-1 flex flex-col lg:flex-row overflow-hidden h-full">
        
        {/* Editor Pane */}
        <div className="w-full lg:flex-1 flex flex-col h-[50vh] lg:h-full border-b lg:border-b-0 lg:border-r border-white/10 relative">
          
          <div className={`flex-none px-4 py-2 border-b flex items-center justify-between overflow-x-auto ${theme === 'dark' ? 'bg-[#0f0f0f] border-white/5' : 'bg-slate-100/50 border-slate-200'}`}>
             <div className="flex items-center gap-4 shrink-0">
                <div className="flex items-center gap-2 text-xs font-mono opacity-50 px-2">
                  <TerminalSquare size={14} /> contract.pact
                </div>
                <div className="w-px h-4 bg-slate-500/30"></div>
                <button onClick={() => setPactCode(EXAMPLES.vulnerable)} className="text-[10px] font-bold px-3 py-1.5 bg-rose-500/10 text-rose-500 rounded-md hover:bg-rose-500/20 transition-all">
                  Load Vulnerable
                </button>
                <button onClick={() => setPactCode(EXAMPLES.multistep)} className="text-[10px] font-bold px-3 py-1.5 bg-amber-500/10 text-amber-500 rounded-md hover:bg-amber-500/20 transition-all">
                  Load Defpact
                </button>
                <button onClick={() => setPactCode(EXAMPLES.secure)} className="text-[10px] font-bold px-3 py-1.5 bg-emerald-500/10 text-emerald-500 rounded-md hover:bg-emerald-500/20 transition-all">
                  Load Secure
                </button>
             </div>
             <button onClick={() => setPactCode("")} className="p-2 opacity-40 hover:opacity-100 hover:text-rose-500 transition-all">
                <Trash2 size={14} />
             </button>
          </div>
          
          <div className={`flex-1 relative overflow-hidden ${theme === 'dark' ? 'bg-[#0A0A0A]' : 'bg-white'}`}>
            {!pactCode && (
              <div className="absolute inset-0 z-10 pointer-events-none flex items-center justify-center flex-col gap-3 opacity-20">
                <Code2 className="w-16 h-16" />
                <p className="text-sm font-black uppercase tracking-widest">Awaiting Pact Code</p>
              </div>
            )}
            <Editor
              height="100%"
              defaultLanguage="clojure"
              theme={theme === 'dark' ? "vs-dark" : "light"}
              value={pactCode}
              onChange={(v) => setPactCode(v || "")}
              options={{
                minimap: { enabled: true, scale: 0.75 },
                fontSize: 14,
                fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
                lineNumbers: "on",
                padding: { top: 20 },
                wordWrap: "on",
                automaticLayout: true,
                cursorBlinking: "smooth",
                smoothScrolling: true,
              }}
            />
          </div>
        </div>

        {/* Results Pane */}
        <div className={`w-full lg:w-[550px] flex flex-col h-[50vh] lg:h-full ${theme === 'dark' ? 'bg-[#0A0A0A]' : 'bg-slate-50'}`}>
          
          {/* Sub-Tabs */}
          <div className={`flex items-center px-6 pt-4 border-b ${theme === 'dark' ? 'border-white/10' : 'border-slate-200'} gap-6`}>
            <button 
              onClick={() => setActiveTab('audit')}
              className={`pb-3 text-xs font-bold uppercase tracking-widest border-b-2 transition-all ${activeTab === 'audit' ? 'border-emerald-500 text-emerald-500' : 'border-transparent opacity-40 hover:opacity-100'}`}
            >
              Security Audit
            </button>
            <button 
              onClick={() => setActiveTab('verification')}
              className={`pb-3 text-xs font-bold uppercase tracking-widest border-b-2 transition-all ${activeTab === 'verification' ? 'border-blue-500 text-blue-500' : 'border-transparent opacity-40 hover:opacity-100'}`}
            >
              Formal Verification
            </button>
          </div>

          <div className="p-6 flex-1 overflow-y-auto custom-scrollbar">
            
            {!findings && !isAnalyzing && (
              <div className="flex flex-col items-center justify-center h-full text-center opacity-30">
                <Search className="w-12 h-12 mb-4" />
                <h3 className="text-sm font-bold uppercase tracking-widest">Analysis Engine Idle</h3>
                <p className="text-xs mt-2 max-w-[250px]">Paste a smart contract and run the audit to generate security metrics.</p>
              </div>
            )}

            {isAnalyzing && (
              <div className="space-y-6">
                <div className={`h-32 rounded-2xl animate-pulse ${theme === 'dark' ? 'bg-white/5' : 'bg-slate-200/60'}`} />
                <div className={`h-40 rounded-2xl animate-pulse delay-75 ${theme === 'dark' ? 'bg-white/5' : 'bg-slate-200/60'}`} />
              </div>
            )}

            {findings && activeTab === 'audit' && (
              <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
                
                {/* Executive Score Dashboard */}
                <div className={`p-6 rounded-3xl border flex items-center justify-between shadow-2xl relative overflow-hidden ${theme === 'dark' ? 'bg-[#111] border-white/10' : 'bg-white border-slate-200'}`}>
                  <div className="absolute top-0 left-0 w-1 bg-gradient-to-b from-emerald-500 to-emerald-900 h-full"></div>
                  <div>
                    <p className="text-[10px] font-black opacity-50 uppercase tracking-widest mb-1">Contract Trust Score</p>
                    <div className="flex items-baseline gap-2">
                      <h3 className={`text-5xl font-black ${score > 70 ? 'text-emerald-500' : score > 40 ? 'text-amber-500' : 'text-rose-500'}`}>{score}</h3>
                      <span className="text-sm font-bold opacity-40">/ 100</span>
                    </div>
                  </div>
                  
                  {/* Radial Progress Chart */}
                  <div className="relative w-24 h-24 flex items-center justify-center">
                    <svg className="w-full h-full transform -rotate-90">
                      <circle cx="48" cy="48" r={radius} stroke="currentColor" strokeWidth="6" fill="transparent" className="opacity-10" />
                      <circle 
                        cx="48" cy="48" r={radius} 
                        stroke="currentColor" strokeWidth="6" fill="transparent" 
                        strokeDasharray={circumference} strokeDashoffset={strokeDashoffset} 
                        className={`transition-all duration-1000 ease-out ${score > 70 ? 'text-emerald-500' : score > 40 ? 'text-amber-500' : 'text-rose-500'}`} 
                      />
                    </svg>
                    <div className="absolute inset-0 flex items-center justify-center">
                      {score > 70 ? <ShieldCheck className="w-8 h-8 text-emerald-500" /> : <AlertOctagon className="w-8 h-8 text-rose-500" />}
                    </div>
                  </div>
                </div>

                {/* Findings List */}
                <h3 className="text-xs font-bold uppercase tracking-widest opacity-40 mt-8 mb-4">Detected Vulnerabilities</h3>
                
                {findings.length === 0 ? (
                  <div className="bg-emerald-500/5 border border-emerald-500/20 rounded-3xl p-8 text-center">
                    <CheckCircle className="w-12 h-12 text-emerald-500 mx-auto mb-4" />
                    <p className="font-black text-emerald-500 uppercase tracking-widest">Zero Vulnerabilities Found</p>
                  </div>
                ) : (
                  findings.map((f, i) => (
                    <div key={i} className={`rounded-3xl border p-6 transition-all relative overflow-hidden group ${
                      theme === 'dark' 
                        ? f.severity === 'High' ? 'bg-rose-500/5 border-rose-500/20 shadow-[0_0_20px_rgba(244,63,94,0.05)]' 
                        : f.severity === 'Medium' ? 'bg-amber-500/5 border-amber-500/20' : 'bg-blue-500/5 border-blue-500/20'
                        : 'bg-white shadow-sm border-slate-200'
                    }`}>
                      <div className={`absolute left-0 top-0 w-1 h-full ${f.severity === 'High' ? 'bg-rose-500' : f.severity === 'Medium' ? 'bg-amber-500' : 'bg-blue-500'}`}></div>
                      
                      <div className="flex justify-between items-start mb-4 pl-2">
                        <div className="flex items-center gap-3">
                          <span className={`text-[10px] font-black px-3 py-1 rounded-md uppercase tracking-wider ${
                            f.severity === 'High' ? 'bg-rose-500 text-white' : 
                            f.severity === 'Medium' ? 'bg-amber-500 text-white' : 'bg-blue-500 text-white'
                          }`}>{f.severity} Risk</span>
                          <span className="text-[10px] font-mono opacity-50 bg-white/5 px-2 py-1 rounded">fn: {f.function_name}</span>
                        </div>
                      </div>
                      
                      <h3 className="font-bold text-lg mb-2 pl-2">{f.issue_title}</h3>
                      <p className="text-sm opacity-70 leading-relaxed mb-6 pl-2">{f.explanation}</p>
                      
                      <div className="mt-4 border-t border-white/5 pt-4 pl-2">
                        <p className="text-[10px] font-bold opacity-40 uppercase tracking-widest mb-3 flex items-center gap-2">
                          Suggested Remediation <ArrowRight size={10} />
                        </p>
                        <div className={`relative rounded-xl p-4 font-mono text-xs border transition-colors duration-500 ${
                          theme === 'dark' 
                            ? 'bg-black/40 border-white/10 text-emerald-400 group-hover:border-emerald-500/30' 
                            : 'bg-white border-slate-200 text-emerald-700 group-hover:border-emerald-500/40 shadow-inner'
                        }`}>
                          <button onClick={() => copyToClipboard(f.recommendation)} className={`absolute top-2 right-2 p-2 rounded-lg transition-colors duration-500 ${
                            theme === 'dark'
                              ? 'bg-white/5 hover:bg-emerald-500/20 hover:text-emerald-400'
                              : 'bg-slate-100 hover:bg-emerald-100 text-emerald-700'
                          }`}>
                            <Copy className="w-4 h-4" />
                          </button>
                          <pre className="whitespace-pre-wrap"><code>{f.recommendation}</code></pre>
                        </div>
                      </div>
                    </div>
                  ))
                )}
              </div>
            )}

            {/* Formal Verification Tab */}
            {findings && activeTab === 'verification' && (
              <div className="space-y-4 animate-in fade-in slide-in-from-bottom-4 duration-500">
                 {findings.filter(f => f.fv_property).length === 0 ? (
                    <div className="text-center opacity-40 py-10 text-sm font-mono">No mathematical proofs generated for this contract.</div>
                 ) : (
                    findings.filter(f => f.fv_property).map((f, i) => (
                      <div key={i} className={`p-6 rounded-2xl border ${theme === 'dark' ? 'bg-blue-900/10 border-blue-500/20' : 'bg-blue-50 border-blue-200'}`}>
                        <div className="flex items-center gap-2 mb-3 text-blue-500">
                          <Zap size={16} />
                          <h4 className="text-xs font-black uppercase tracking-widest">Pact Property Proof</h4>
                        </div>
                        <p className="text-sm opacity-70 mb-4">The following mathematical property must hold true for `{f.function_name}`:</p>
                        <code className="block p-4 rounded-xl bg-black/50 border border-black/50 text-blue-400 font-mono text-xs">
                          {f.fv_property}
                        </code>
                      </div>
                    ))
                 )}
              </div>
            )}

          </div>
        </div>
      </main>
    </div>
  );
}